#!/usr/bin/env python3.12
"""
Build the labelled error corpus at docs/20260408-0623_classifier_prd/error_corpus.jsonl.

Each row is a real-world-phrased error a dev would paste into `borg debug "<...>"`.
Records are sourced from official docs, GitHub issues, Stack Overflow, and general
knowledge of these ecosystems. No synthetic gibberish.

Schema:
  id, language, framework, family, text, source, expected_problem_class, expected_action

expected_problem_class is what a well-designed, language-aware classifier SHOULD
return. For Python errors currently in the taxonomy we reuse existing classes
(null_pointer_chain, missing_dependency, type_mismatch, ...) so backwards
compatibility is measurable. For new languages/areas we use PROPOSED new classes
(rust_borrow_checker, docker_disk_full, k8s_crashloop, ...) which the current
classifier cannot possibly emit — so they're the "silent miss" (honest) vs
"false confident" (harmful) dividing line.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import List, Tuple

OUT = Path(__file__).parent / "error_corpus.jsonl"


# Fields per entry (positional for compactness):
#   language, framework, family, text, source, expected_problem_class, expected_action
Entry = Tuple[str, str | None, str, str, str, str | None, str]


# ============================================================================
# PYTHON — 34 entries
# ============================================================================
# Mix of Django, Flask, FastAPI, and generic Python. Where the CURRENT taxonomy
# already has a reasonable home (null_pointer_chain, missing_dependency,
# migration_state_desync, etc.), we use it — so success/regression is measurable.

PYTHON: List[Entry] = [
    # --- generic Python ---
    ("python", None, "null_deref",
     "AttributeError: 'NoneType' object has no attribute 'split'",
     "stackoverflow.com/q/8949252", "null_pointer_chain",
     "trace which call returned None; add a None check or default value"),
    ("python", None, "null_deref",
     "TypeError: 'NoneType' object is not iterable",
     "python docs tutorial", "null_pointer_chain",
     "trace which function returned None where an iterable was expected"),
    ("python", None, "null_deref",
     "AttributeError: 'NoneType' object has no attribute 'get'",
     "django GitHub issue", "null_pointer_chain",
     "the dict-like object is None; check upstream assignment"),
    ("python", None, "missing_module",
     "ModuleNotFoundError: No module named 'requests'",
     "pypa docs", "missing_dependency",
     "pip install requests and add to requirements/pyproject"),
    ("python", None, "missing_module",
     "ImportError: cannot import name 'soft_unicode' from 'markupsafe'",
     "flask 2.x upgrade issue", "missing_dependency",
     "pin markupsafe<2.1 or upgrade flask"),
    ("python", None, "missing_module",
     "ModuleNotFoundError: No module named 'numpy'",
     "pypa docs", "missing_dependency",
     "pip install numpy into the active venv"),
    ("python", None, "type_mismatch",
     "TypeError: unsupported operand type(s) for +: 'int' and 'str'",
     "python docs tutorial", "type_mismatch",
     "explicitly cast with str() or int() before concatenation"),
    ("python", None, "type_mismatch",
     "TypeError: list indices must be integers or slices, not str",
     "python docs", "type_mismatch",
     "you probably meant a dict; check the data structure"),
    ("python", None, "import_cycle",
     "ImportError: cannot import name 'User' from partially initialized module 'app.models' (most likely due to a circular import)",
     "python docs / flask issue", "import_cycle",
     "move import inside function or restructure modules"),
    ("python", None, "key_error",
     "KeyError: 'user_id'",
     "flask stackoverflow", "python_key_error",
     "use dict.get() with default, or validate key presence before access"),
    ("python", None, "index_error",
     "IndexError: list index out of range",
     "python docs", "python_index_error",
     "check len() before indexing or use try/except"),
    ("python", None, "value_error",
     "ValueError: invalid literal for int() with base 10: 'abc'",
     "python docs", "python_value_error",
     "validate input before parsing; use try/except ValueError"),
    ("python", None, "value_error",
     "ValueError: too many values to unpack (expected 2)",
     "python docs", "python_value_error",
     "check the shape of the tuple/iterable being unpacked"),
    ("python", None, "syntax_error",
     "SyntaxError: invalid syntax",
     "python docs", "python_syntax_error",
     "look at the line and the one above for unmatched parens/quotes"),
    ("python", None, "indentation",
     "IndentationError: unexpected indent",
     "python docs", "python_syntax_error",
     "normalize tabs vs spaces; configure editor to spaces"),
    ("python", None, "recursion",
     "RecursionError: maximum recursion depth exceeded while calling a Python object",
     "python docs", "python_recursion_error",
     "find the missing base case or convert to iterative"),
    ("python", None, "file_not_found",
     "FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'",
     "python docs", "python_file_not_found",
     "use absolute path or verify cwd; check file exists first"),
    ("python", None, "permission",
     "PermissionError: [Errno 13] Permission denied: '/var/log/app.log'",
     "python docs", "permission_denied",
     "run as correct user or chmod/chown the file"),
    ("python", None, "encoding",
     "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte",
     "python docs", "python_encoding_error",
     "open file with correct encoding or errors='replace'"),
    ("python", None, "timeout",
     "socket.timeout: timed out",
     "python urllib docs", "timeout_hang",
     "increase timeout or add retry; check network/service health"),
    ("python", None, "assertion",
     "AssertionError",
     "pytest docs", "python_assertion_error",
     "inspect the failing assertion; run pytest -x --tb=long"),
    # --- Django ---
    ("python", "django", "django_settings",
     "django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.",
     "django docs", "configuration_error",
     "set SECRET_KEY via env var or settings.py"),
    ("python", "django", "django_settings",
     "django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header. You may need to add to ALLOWED_HOSTS.",
     "django docs", "configuration_error",
     "add host to ALLOWED_HOSTS in settings.py"),
    ("python", "django", "django_migration",
     "django.db.utils.OperationalError: no such column: auth_user.is_active",
     "django ticket tracker", "schema_drift",
     "run python manage.py migrate; investigate drifted migration"),
    ("python", "django", "django_migration",
     "You have 3 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes.",
     "django startup warning", "migration_state_desync",
     "run python manage.py migrate"),
    ("python", "django", "django_migration",
     "django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency auth.0001_initial",
     "django docs", "migration_state_desync",
     "review migration graph; may need --fake or squash"),
    ("python", "django", "django_orm",
     "django.db.utils.IntegrityError: FOREIGN KEY constraint failed",
     "django docs", "missing_foreign_key",
     "ensure referenced row exists; add null/on_delete"),
    ("python", "django", "django_orm",
     "django.core.exceptions.FieldError: Cannot resolve keyword 'usernam' into field. Choices are: username, email, ...",
     "django QuerySet docs", "python_field_error",
     "fix the typo in .filter()/.get() keyword"),
    ("python", "django", "django_orm",
     "MyModel.DoesNotExist: MyModel matching query does not exist.",
     "django ORM docs", "python_does_not_exist",
     "use get_object_or_404 or .filter().first() with None check"),
    # --- Flask ---
    ("python", "flask", "flask_routing",
     "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?",
     "flask docs", "python_routing_error",
     "use blueprint-qualified endpoint name in url_for"),
    ("python", "flask", "flask_context",
     "RuntimeError: Working outside of application context.",
     "flask docs", "python_flask_context",
     "wrap in app.app_context() or use current_app properly"),
    # --- FastAPI / Pydantic ---
    ("python", "fastapi", "pydantic_validation",
     "pydantic.error_wrappers.ValidationError: 1 validation error for User\nage\n  value is not a valid integer (type=type_error.integer)",
     "fastapi docs", "python_pydantic_validation",
     "check request payload; fix client or loosen schema"),
    ("python", "fastapi", "pydantic_validation",
     "fastapi.exceptions.RequestValidationError: [{'loc': ['body', 'email'], 'msg': 'field required', 'type': 'value_error.missing'}]",
     "fastapi issues", "python_pydantic_validation",
     "client must send the missing field or mark Optional"),
    ("python", "fastapi", "async_error",
     "RuntimeError: asyncio.run() cannot be called from a running event loop",
     "python asyncio docs", "python_async_error",
     "use await directly or asyncio.ensure_future in running loop"),
]


# ============================================================================
# JAVASCRIPT — 22 entries (browser + Node)
# ============================================================================
JAVASCRIPT: List[Entry] = [
    ("javascript", None, "undefined_access",
     "TypeError: Cannot read properties of undefined (reading 'map')",
     "MDN / stackoverflow", "js_undefined_property",
     "the variable is undefined; add optional chaining ?. or default"),
    ("javascript", None, "undefined_access",
     "TypeError: Cannot read property 'length' of null",
     "MDN", "js_undefined_property",
     "null-check before access or use ?? default"),
    ("javascript", None, "reference_error",
     "ReferenceError: foo is not defined",
     "MDN", "js_reference_error",
     "check spelling/scope; missing import or declaration"),
    ("javascript", None, "reference_error",
     "ReferenceError: window is not defined",
     "next.js SSR issues", "js_ssr_reference_error",
     "guard with typeof window !== 'undefined' or move to useEffect"),
    ("javascript", None, "reference_error",
     "ReferenceError: document is not defined",
     "nodejs issues", "js_ssr_reference_error",
     "code ran server-side; move DOM access into client-only path"),
    ("javascript", None, "syntax_error",
     "SyntaxError: Unexpected token '<'",
     "stackoverflow classic", "js_syntax_error",
     "you fetched HTML (likely 404) and tried to JSON.parse it"),
    ("javascript", None, "syntax_error",
     "SyntaxError: Unexpected end of JSON input",
     "MDN JSON", "js_json_parse_error",
     "response body was empty; check network + status"),
    ("javascript", None, "type_error",
     "TypeError: foo.map is not a function",
     "MDN", "js_type_error",
     "foo is not an array; log its type and upstream source"),
    ("javascript", None, "type_error",
     "TypeError: Assignment to constant variable.",
     "MDN", "js_type_error",
     "change const to let or avoid reassignment"),
    ("javascript", None, "type_error",
     "TypeError: Converting circular structure to JSON",
     "node docs", "js_json_circular",
     "remove cycles or use a replacer / flatted"),
    ("javascript", None, "async_unhandled",
     "UnhandledPromiseRejectionWarning: Unhandled promise rejection.",
     "node docs", "js_unhandled_promise",
     "add .catch() or try/await; enable unhandledRejection handler"),
    ("javascript", "node", "module_not_found",
     "Error: Cannot find module 'express'",
     "nodejs docs", "js_module_not_found",
     "npm install express; check package.json and node_modules"),
    ("javascript", "node", "module_not_found",
     "Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'lodash' imported from /app/index.mjs",
     "nodejs ESM docs", "js_module_not_found",
     "npm install lodash; add package to dependencies"),
    ("javascript", "node", "esm_cjs",
     "Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/chalk/source/index.js not supported.",
     "nodejs ESM docs", "js_esm_cjs_mismatch",
     "pin chalk<5 or convert project to ESM"),
    ("javascript", "node", "port_in_use",
     "Error: listen EADDRINUSE: address already in use :::3000",
     "nodejs docs", "js_port_in_use",
     "kill other process on port 3000 or pick another port"),
    ("javascript", "node", "connection_refused",
     "Error: connect ECONNREFUSED 127.0.0.1:5432",
     "pg driver issues", "timeout_hang",
     "the target service is not running; start it or fix URL"),
    ("javascript", None, "cors_error",
     "Access to fetch at 'https://api.example.com' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.",
     "MDN CORS", "js_cors_error",
     "add CORS headers on server or proxy through your own backend"),
    ("javascript", None, "promise_await",
     "TypeError: Cannot read properties of undefined (reading 'then')",
     "stackoverflow", "js_missing_await",
     "you forgot to return the promise or await'd a non-promise"),
    ("javascript", None, "memory",
     "FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory",
     "nodejs v8 docs", "js_heap_oom",
     "increase --max-old-space-size or find the leak"),
    ("javascript", None, "encoding",
     "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data",
     "MDN JSON", "js_json_parse_error",
     "response is not JSON; log the raw text first"),
    ("javascript", None, "stack_overflow",
     "RangeError: Maximum call stack size exceeded",
     "MDN", "js_stack_overflow",
     "infinite recursion; find the base case"),
    ("javascript", "node", "fs_error",
     "Error: ENOENT: no such file or directory, open '/app/config.json'",
     "nodejs fs docs", "js_file_not_found",
     "verify path; use path.resolve + fs.existsSync"),
]


# ============================================================================
# TYPESCRIPT — 20 entries
# ============================================================================
TYPESCRIPT: List[Entry] = [
    ("typescript", None, "ts_type_assign",
     "TS2322: Type 'string' is not assignable to type 'number'.",
     "typescript docs", "ts_type_error",
     "cast, parse, or correct the declared type"),
    ("typescript", None, "ts_type_assign",
     "TS2322: Type 'null' is not assignable to type 'string'.",
     "ts strict null checks", "ts_null_check",
     "narrow with if, use ?? default, or change type to string | null"),
    ("typescript", None, "ts_prop_missing",
     "TS2339: Property 'name' does not exist on type '{}'.",
     "typescript docs", "ts_property_missing",
     "declare an interface or use a type assertion"),
    ("typescript", None, "ts_prop_missing",
     "TS2551: Property 'lenght' does not exist on type 'string'. Did you mean 'length'?",
     "typescript docs", "ts_property_missing",
     "fix the typo (length)"),
    ("typescript", None, "ts_implicit_any",
     "TS7006: Parameter 'req' implicitly has an 'any' type.",
     "typescript docs noImplicitAny", "ts_implicit_any",
     "annotate parameter type"),
    ("typescript", None, "ts_arg_count",
     "TS2554: Expected 2 arguments, but got 1.",
     "typescript docs", "ts_argument_error",
     "pass the missing argument or make it optional in the signature"),
    ("typescript", None, "ts_arg_type",
     "TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.",
     "typescript docs", "ts_type_error",
     "convert the argument or fix the function signature"),
    ("typescript", None, "ts_strict_null",
     "TS2531: Object is possibly 'null'.",
     "ts strict null checks", "ts_null_check",
     "guard with if (x), use ! if you know better, or ?. chaining"),
    ("typescript", None, "ts_strict_null",
     "TS2532: Object is possibly 'undefined'.",
     "ts strict null checks", "ts_null_check",
     "narrow or optional-chain"),
    ("typescript", None, "ts_strict_null",
     "TS18048: 'user' is possibly 'undefined'.",
     "typescript 4.8+", "ts_null_check",
     "add a guard or ?."),
    ("typescript", None, "ts_module",
     "TS2307: Cannot find module 'foo' or its corresponding type declarations.",
     "typescript docs", "ts_module_resolution",
     "npm install foo; add @types/foo or declare module"),
    ("typescript", None, "ts_module",
     "TS2691: An import path cannot end with a '.ts' extension.",
     "typescript docs", "ts_module_resolution",
     "drop the .ts from the import specifier"),
    ("typescript", None, "ts_generic",
     "TS2344: Type 'X' does not satisfy the constraint 'Y'.",
     "typescript docs", "ts_generic_constraint",
     "ensure the generic type extends the constraint"),
    ("typescript", None, "ts_declaration",
     "TS1192: Module '\"./foo\"' has no default export.",
     "typescript docs", "ts_module_resolution",
     "use named import { bar } or add default export"),
    ("typescript", None, "ts_jsx",
     "TS2304: Cannot find name 'React'.",
     "ts + jsx", "ts_module_resolution",
     "import React or configure jsx: 'react-jsx' in tsconfig"),
    ("typescript", None, "ts_never",
     "TS2367: This condition will always return 'false' since the types have no overlap.",
     "typescript docs", "ts_type_error",
     "remove dead comparison or fix the types"),
    ("typescript", None, "ts_return",
     "TS7030: Not all code paths return a value.",
     "typescript docs noImplicitReturns", "ts_type_error",
     "add explicit return on every branch"),
    ("typescript", None, "ts_config",
     "TS5023: Unknown compiler option 'strictNullCkecks'. Did you mean 'strictNullChecks'?",
     "typescript docs", "ts_config_error",
     "fix typo in tsconfig.json"),
    ("typescript", None, "ts_never_narrow",
     "TS2322: Type 'X' is not assignable to type 'never'.",
     "typescript exhaustiveness", "ts_exhaustiveness",
     "add the missing case in switch/assertNever"),
    ("typescript", None, "ts_unused",
     "TS6133: 'foo' is declared but its value is never read.",
     "ts noUnusedLocals", "ts_lint_error",
     "remove unused local or prefix with _"),
]


# ============================================================================
# REACT / NEXT.JS — 16 entries
# ============================================================================
REACT: List[Entry] = [
    ("javascript", "react", "hydration",
     "Error: Hydration failed because the initial UI does not match what was rendered on the server.",
     "react docs / next.js", "react_hydration_mismatch",
     "ensure server and client render identical markup; guard Date/random"),
    ("javascript", "react", "hydration",
     "Warning: Text content did not match. Server: \"0\" Client: \"1\"",
     "react docs", "react_hydration_mismatch",
     "avoid non-deterministic values during SSR; use suppressHydrationWarning sparingly"),
    ("javascript", "react", "hooks_rule",
     "Error: Invalid hook call. Hooks can only be called inside of the body of a function component.",
     "react docs", "react_hooks_rule_violation",
     "check react/react-dom versions match; don't call hooks conditionally"),
    ("javascript", "react", "hooks_rule",
     "React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array. (react-hooks/exhaustive-deps)",
     "eslint-plugin-react-hooks", "react_hooks_deps",
     "add the dependency, memoize it, or justify the exclusion"),
    ("javascript", "react", "missing_key",
     "Warning: Each child in a list should have a unique \"key\" prop.",
     "react docs", "react_missing_key",
     "add stable key prop (not array index for reordering lists)"),
    ("javascript", "react", "state_after_unmount",
     "Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application.",
     "react docs (pre-18)", "react_unmounted_state",
     "cancel async work in useEffect cleanup or use AbortController"),
    ("javascript", "react", "infinite_rerender",
     "Error: Too many re-renders. React limits the number of renders to prevent an infinite loop.",
     "react docs", "react_infinite_rerender",
     "you called setState unconditionally during render; move to effect/handler"),
    ("javascript", "react", "missing_provider",
     "Error: useContext must be used within a Provider",
     "react docs", "react_missing_provider",
     "wrap the tree in the corresponding Context.Provider"),
    ("javascript", "react", "controlled_component",
     "Warning: A component is changing an uncontrolled input to be controlled.",
     "react docs", "react_controlled_input",
     "initialize state with '' instead of undefined"),
    ("javascript", "nextjs", "nextjs_use_client",
     "Error: You're importing a component that needs useState. It only works in a Client Component but none of its parents are marked with \"use client\"",
     "next.js 13 docs", "nextjs_use_client",
     "add 'use client' directive at top of the file"),
    ("javascript", "nextjs", "nextjs_use_client",
     "Error: useRouter only works in Client Components. Add the \"use client\" directive at the top of the file to use it.",
     "next.js 13 docs", "nextjs_use_client",
     "add 'use client' or switch to next/navigation on server"),
    ("javascript", "nextjs", "nextjs_build",
     "Error: Failed to collect page data for /api/foo",
     "next.js issues", "nextjs_build_error",
     "check the route's default export and runtime imports"),
    ("javascript", "nextjs", "nextjs_routing",
     "Error: No router instance found. You should only use \"next/router\" inside the client side of your app.",
     "next.js docs", "nextjs_routing_error",
     "import from next/navigation in app router or guard with typeof window"),
    ("javascript", "nextjs", "nextjs_image",
     "Error: Invalid src prop (https://foo.com/a.png) on `next/image`, hostname \"foo.com\" is not configured under images in your `next.config.js`",
     "next.js docs", "nextjs_image_config",
     "add remotePatterns/domains to next.config.js"),
    ("javascript", "react", "suspense",
     "Error: A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator.",
     "react 18 docs", "react_suspense_sync",
     "wrap state update in startTransition or move data fetching"),
    ("javascript", "react", "key_warning_detail",
     "Warning: Encountered two children with the same key, `foo`. Keys should be unique so that components maintain their identity across updates.",
     "react docs", "react_missing_key",
     "ensure keys are unique; derive from id not title"),
]


# ============================================================================
# RUST — 22 entries
# ============================================================================
RUST: List[Entry] = [
    ("rust", None, "borrow_checker",
     "error[E0382]: borrow of moved value: `x`",
     "rust-lang error index", "rust_borrow_checker",
     "clone, borrow by reference, or restructure ownership"),
    ("rust", None, "borrow_checker",
     "error[E0382]: use of moved value: `s`",
     "rust-lang error index", "rust_borrow_checker",
     "use s.clone() before the first move or borrow instead"),
    ("rust", None, "borrow_checker",
     "error[E0502]: cannot borrow `v` as mutable because it is also borrowed as immutable",
     "rust-lang error index", "rust_borrow_checker",
     "scope the immutable borrow smaller or clone first"),
    ("rust", None, "borrow_checker",
     "error[E0499]: cannot borrow `self` as mutable more than once at a time",
     "rust-lang error index", "rust_borrow_checker",
     "use split_at_mut, RefCell, or restructure"),
    ("rust", None, "lifetime",
     "error[E0106]: missing lifetime specifier",
     "rust-lang error index", "rust_lifetime_error",
     "add explicit 'a lifetime on the reference"),
    ("rust", None, "lifetime",
     "error[E0597]: `data` does not live long enough",
     "rust-lang error index", "rust_lifetime_error",
     "extend scope of data or return owned value"),
    ("rust", None, "lifetime",
     "error[E0621]: explicit lifetime required in the type of `x`",
     "rust-lang error index", "rust_lifetime_error",
     "annotate the struct/function with a named lifetime"),
    ("rust", None, "trait_bound",
     "error[E0277]: the trait bound `MyType: Send` is not satisfied",
     "rust-lang error index", "rust_trait_bound",
     "make fields Send or wrap in Mutex; derive/impl as needed"),
    ("rust", None, "trait_bound",
     "error[E0277]: `Rc<T>` cannot be sent between threads safely",
     "rust async book", "rust_trait_bound",
     "use Arc instead of Rc for cross-thread sharing"),
    ("rust", None, "trait_bound",
     "error[E0277]: the trait bound `T: std::fmt::Display` is not satisfied",
     "rust book", "rust_trait_bound",
     "add `where T: Display` bound or impl Display"),
    ("rust", None, "async_send",
     "error: future cannot be sent between threads safely within `impl Future`, the trait `Send` is not implemented for `Rc<...>`",
     "tokio issues", "rust_async_send",
     "replace Rc with Arc; MutexGuard must not cross .await"),
    ("rust", None, "async_pin",
     "error[E0277]: `from_generator::GenFuture<...>` cannot be unpinned",
     "rust async issues", "rust_async_pin",
     "use Box::pin or tokio::pin!"),
    ("rust", None, "mismatched_types",
     "error[E0308]: mismatched types: expected `&str`, found `String`",
     "rust-lang error index", "rust_mismatched_types",
     "use &s or s.as_str()"),
    ("rust", None, "mismatched_types",
     "error[E0308]: mismatched types: expected `u32`, found `i32`",
     "rust-lang error index", "rust_mismatched_types",
     "cast with `as u32` or change the integer literal suffix"),
    ("rust", None, "unwrap_panic",
     "thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'",
     "rust by example", "rust_unwrap_panic",
     "use match / if let / unwrap_or instead of unwrap"),
    ("rust", None, "unwrap_panic",
     "thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { ... }'",
     "rust stdlib", "rust_unwrap_panic",
     "propagate with ? or handle the Err branch"),
    ("rust", None, "move_closure",
     "error[E0373]: closure may outlive the current function, but it borrows `s`, which is owned by the current function",
     "rust-lang error index", "rust_closure_move",
     "use `move ||` to move ownership into the closure"),
    ("rust", None, "cargo_build",
     "error: linker `cc` not found",
     "rustup install", "rust_toolchain_error",
     "install build-essential / Xcode CLT / MSVC Build Tools"),
    ("rust", None, "cargo_build",
     "error: could not compile `openssl-sys` due to previous error",
     "rust common", "rust_toolchain_error",
     "install libssl-dev / pkg-config or use rustls feature"),
    ("rust", None, "cargo_resolve",
     "error: failed to select a version for the requirement `tokio = \"^2.0\"`",
     "cargo docs", "cargo_resolve_error",
     "check crates.io for actual versions; fix Cargo.toml"),
    ("rust", None, "pattern_match",
     "error[E0004]: non-exhaustive patterns: `None` not covered",
     "rust-lang error index", "rust_non_exhaustive",
     "add None arm or `_ =>` fallback"),
    ("rust", None, "type_inference",
     "error[E0282]: type annotations needed",
     "rust-lang error index", "rust_type_annotation",
     "annotate let binding with an explicit type"),
]


# ============================================================================
# GO — 16 entries
# ============================================================================
GO: List[Entry] = [
    ("go", None, "nil_deref",
     "panic: runtime error: invalid memory address or nil pointer dereference",
     "go runtime", "go_nil_pointer",
     "trace the nil; add nil-check before access"),
    ("go", None, "nil_deref",
     "panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x]",
     "go runtime", "go_nil_pointer",
     "look at goroutine stack trace above for the nil receiver"),
    ("go", None, "slice_bounds",
     "panic: runtime error: index out of range [5] with length 3",
     "go runtime", "go_index_out_of_range",
     "bounds-check before indexing"),
    ("go", None, "type_assertion",
     "panic: interface conversion: interface {} is string, not int",
     "go runtime", "go_type_assertion",
     "use the comma-ok form: v, ok := x.(int)"),
    ("go", None, "data_race",
     "WARNING: DATA RACE\nRead at 0x00c0000a8010 by goroutine 7:\nPrevious write at 0x00c0000a8010 by goroutine 6:",
     "go race detector", "go_data_race",
     "protect shared state with sync.Mutex or use channels"),
    ("go", None, "deadlock",
     "fatal error: all goroutines are asleep - deadlock!",
     "go runtime", "go_deadlock",
     "unbuffered channel has no receiver; review channel flow"),
    ("go", None, "goroutine_leak",
     "goroutine 123 [chan receive, 5 minutes]:\nmain.worker(...)",
     "pprof output", "go_goroutine_leak",
     "ensure channels are closed or goroutines have exit path"),
    ("go", None, "import_cycle",
     "import cycle not allowed\npackage foo imports bar imports foo",
     "go build", "go_import_cycle",
     "extract shared types to a third package"),
    ("go", None, "module_error",
     "go: module github.com/foo/bar: reading https://proxy.golang.org/...: 404 Not Found",
     "go modules", "go_module_error",
     "check module path and version; go mod tidy"),
    ("go", None, "module_error",
     "go: cannot find main module, but found .git/config in /home/me/proj",
     "go modules", "go_module_error",
     "run go mod init"),
    ("go", None, "compile_error",
     "./main.go:10:2: undefined: fmt.Printl",
     "go build", "go_compile_error",
     "fix typo: fmt.Println"),
    ("go", None, "compile_error",
     "./main.go:15:9: cannot use x (type string) as type int in return argument",
     "go build", "go_type_mismatch",
     "cast or fix the return type"),
    ("go", None, "http_error",
     "http: panic serving 127.0.0.1:54321: runtime error: invalid memory address or nil pointer dereference",
     "net/http", "go_nil_pointer",
     "nil handler field; initialize before ListenAndServe"),
    ("go", None, "channel_closed",
     "panic: send on closed channel",
     "go runtime", "go_channel_error",
     "ownership rule: only sender closes; use sync.Once or context"),
    ("go", None, "unused_import",
     "./main.go:3:8: imported and not used: \"fmt\"",
     "go build", "go_unused_import",
     "remove unused import or use _"),
    ("go", None, "context_cancel",
     "context deadline exceeded",
     "go context", "timeout_hang",
     "raise timeout or investigate slow dependency"),
]


# ============================================================================
# DOCKER — 16 entries
# ============================================================================
DOCKER: List[Entry] = [
    ("shell", "docker", "disk_full",
     "Error processing tar file(exit status 1): write /foo: no space left on device",
     "docker GitHub issues", "docker_disk_full",
     "docker system prune -af; check /var/lib/docker disk"),
    ("shell", "docker", "disk_full",
     "failed to register layer: Error processing tar file(exit status 1): write /usr/lib: no space left on device",
     "docker build issues", "docker_disk_full",
     "prune unused images/volumes; grow disk"),
    ("shell", "docker", "build_context",
     "ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref ...: \"/app\": not found",
     "buildkit docs", "docker_build_context",
     "check .dockerignore and COPY source path"),
    ("shell", "docker", "build_error",
     "The command '/bin/sh -c apt-get install -y curl' returned a non-zero code: 100",
     "docker docs", "docker_build_error",
     "add apt-get update before install; check package name"),
    ("shell", "docker", "image_not_found",
     "Unable to find image 'nginx:latest' locally\ndocker: Error response from daemon: pull access denied for nginx, repository does not exist or may require 'docker login'",
     "docker docs", "docker_image_not_found",
     "docker login; check repo name and tag"),
    ("shell", "docker", "image_not_found",
     "Error response from daemon: manifest for myimage:v2 not found: manifest unknown",
     "docker registry", "docker_image_not_found",
     "verify tag exists in registry"),
    ("shell", "docker", "port_conflict",
     "docker: Error response from daemon: driver failed programming external connectivity on endpoint foo: Bind for 0.0.0.0:80 failed: port is already allocated.",
     "docker issues", "docker_port_conflict",
     "stop conflicting container or pick another host port"),
    ("shell", "docker", "volume_permission",
     "chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted",
     "postgres docker image", "docker_volume_permission",
     "use named volume or set correct uid/gid"),
    ("shell", "docker", "daemon_error",
     "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?",
     "docker docs", "docker_daemon_error",
     "systemctl start docker; add user to docker group"),
    ("shell", "docker", "network",
     "docker: Error response from daemon: network with name bridge0 already exists",
     "docker network", "docker_network_error",
     "docker network rm or use a different name"),
    ("shell", "docker", "exit_code",
     "container exited with code 137",
     "docker runtime", "docker_oom_killed",
     "exit 137 = OOM kill; raise memory or profile"),
    ("shell", "docker", "build_layer",
     "failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize",
     "buildkit issues", "docker_auth_error",
     "docker login to base image registry"),
    ("shell", "docker", "compose",
     "ERROR: Version in \"./docker-compose.yml\" is unsupported.",
     "compose docs", "docker_compose_error",
     "update compose version or upgrade docker compose"),
    ("shell", "docker", "platform",
     "WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested",
     "docker multi-arch", "docker_platform_mismatch",
     "add --platform or use multi-arch image"),
    ("shell", "docker", "build_error",
     "Step 5/10 : RUN pip install -r requirements.txt\n ---> Running in abc123\nERROR: Could not find a version that satisfies the requirement foo",
     "docker build", "docker_build_error",
     "check Python version / package name / index URL"),
    ("shell", "docker", "overlay",
     "failed to register layer: ApplyLayer exit status 1 stdout: stderr: archive/tar: invalid tar header",
     "docker issues", "docker_layer_error",
     "prune images; pull base fresh"),
]


# ============================================================================
# KUBERNETES — 16 entries
# ============================================================================
K8S: List[Entry] = [
    ("shell", "kubernetes", "crashloop",
     "NAME           READY   STATUS             RESTARTS   AGE\napp-5df7c-xk2   0/1     CrashLoopBackOff   8          10m",
     "k8s docs", "k8s_crashloop",
     "kubectl logs --previous; check exit code and app startup"),
    ("shell", "kubernetes", "crashloop",
     "Back-off restarting failed container app in pod app-5df7c-xk2_default",
     "kubelet events", "k8s_crashloop",
     "check container logs and liveness/readiness probes"),
    ("shell", "kubernetes", "image_pull",
     "Failed to pull image \"myrepo/app:v1\": rpc error: code = Unknown desc = Error response from daemon: pull access denied",
     "kubelet events", "k8s_image_pull_auth",
     "create imagePullSecret; check registry auth"),
    ("shell", "kubernetes", "image_pull",
     "ImagePullBackOff",
     "kubectl get pods", "k8s_image_pull",
     "describe pod to see underlying reason: auth, not found, or DNS"),
    ("shell", "kubernetes", "image_pull",
     "ErrImagePull: rpc error: code = NotFound desc = failed to pull and unpack image \"myrepo/app:v1\": not found",
     "kubelet events", "k8s_image_not_found",
     "verify tag exists in registry"),
    ("shell", "kubernetes", "oom_killed",
     "Last State:     Terminated\n  Reason:       OOMKilled\n  Exit Code:    137",
     "kubectl describe pod", "k8s_oom_killed",
     "raise resources.limits.memory or profile app"),
    ("shell", "kubernetes", "evicted",
     "Status: Failed\nReason: Evicted\nMessage: The node was low on resource: ephemeral-storage. Container app was using 5Gi, which exceeds its request of 0.",
     "kubectl describe pod", "k8s_evicted",
     "set ephemeral-storage requests; clean up /tmp"),
    ("shell", "kubernetes", "config_missing",
     "Error: couldn't find key db-password in Secret default/app-secrets",
     "k8s events", "k8s_config_missing",
     "kubectl create secret or add missing key"),
    ("shell", "kubernetes", "config_missing",
     "MountVolume.SetUp failed for volume \"config\" : configmap \"app-config\" not found",
     "kubelet events", "k8s_config_missing",
     "create the configmap before deploying the pod"),
    ("shell", "kubernetes", "rbac",
     "Error from server (Forbidden): pods is forbidden: User \"system:serviceaccount:default:app-sa\" cannot list resource \"pods\" in API group \"\" in the namespace \"default\"",
     "kubectl error", "k8s_rbac_denied",
     "create Role and RoleBinding granting list on pods"),
    ("shell", "kubernetes", "probe_failed",
     "Readiness probe failed: Get \"http://10.0.0.5:8080/health\": dial tcp 10.0.0.5:8080: connect: connection refused",
     "kubelet events", "k8s_probe_failed",
     "verify app listens on the probed port; initialDelaySeconds"),
    ("shell", "kubernetes", "pvc_pending",
     "pod has unbound immediate PersistentVolumeClaims",
     "kubelet events", "k8s_pvc_pending",
     "check StorageClass exists; describe PVC"),
    ("shell", "kubernetes", "scheduling",
     "0/3 nodes are available: 3 Insufficient cpu.",
     "scheduler events", "k8s_unschedulable",
     "lower request or scale node pool"),
    ("shell", "kubernetes", "scheduling",
     "0/3 nodes are available: 3 node(s) had untolerated taint {node.kubernetes.io/unreachable: }",
     "scheduler events", "k8s_unschedulable",
     "tolerate the taint or fix node networking"),
    ("shell", "kubernetes", "dns",
     "Error: failed to do request: Head \"https://registry-1.docker.io/v2/library/nginx/manifests/latest\": dial tcp: lookup registry-1.docker.io on 10.96.0.10:53: no such host",
     "kubelet / coredns", "k8s_dns_error",
     "check coredns health; verify upstream DNS"),
    ("shell", "kubernetes", "quota",
     "Error creating: pods \"app-\" is forbidden: exceeded quota: compute-resources, requested: limits.memory=2Gi, used: limits.memory=8Gi, limited: limits.memory=8Gi",
     "k8s resource quota", "k8s_resource_quota",
     "raise ResourceQuota or reduce pod limits"),
]


# ============================================================================
# SHELL / OS — 11 entries
# ============================================================================
SHELL: List[Entry] = [
    ("shell", None, "command_not_found",
     "bash: jq: command not found",
     "bash", "shell_command_not_found",
     "apt-get install jq / brew install jq; check PATH"),
    ("shell", None, "command_not_found",
     "zsh: command not found: python",
     "shell", "shell_command_not_found",
     "install python or fix PATH (pyenv, asdf)"),
    ("shell", None, "permission",
     "bash: ./deploy.sh: Permission denied",
     "bash", "permission_denied",
     "chmod +x deploy.sh"),
    ("shell", None, "disk_full",
     "cp: error writing '/backup/db.dump': No space left on device",
     "coreutils", "shell_disk_full",
     "df -h; prune old files; expand volume"),
    ("shell", None, "port_in_use",
     "bind: address already in use",
     "unix sockets", "shell_port_in_use",
     "lsof -i :PORT; kill or pick a new port"),
    ("shell", None, "dns",
     "curl: (6) Could not resolve host: api.example.com",
     "curl", "shell_dns_error",
     "check /etc/resolv.conf; verify network"),
    ("shell", None, "ssl",
     "curl: (60) SSL certificate problem: unable to get local issuer certificate",
     "curl", "shell_ssl_error",
     "update ca-certificates or set CURL_CA_BUNDLE"),
    ("shell", None, "file_not_found",
     "cat: config.yaml: No such file or directory",
     "coreutils", "shell_file_not_found",
     "check pwd and filename"),
    ("shell", None, "oom",
     "Killed",
     "linux oom killer", "shell_oom_killed",
     "check dmesg for OOM; raise memory or optimize"),
    ("shell", None, "segfault",
     "Segmentation fault (core dumped)",
     "linux", "shell_segfault",
     "run under gdb; check for memory corruption / null deref"),
    ("shell", None, "exit_code",
     "make: *** [Makefile:42: build] Error 2",
     "make", "shell_build_error",
     "scroll up — the real error is in the recipe above"),
]


ALL: List[Tuple[str, List[Entry]]] = [
    ("PY", PYTHON),
    ("JS", JAVASCRIPT),
    ("TS", TYPESCRIPT),
    ("RX", REACT),
    ("RS", RUST),
    ("GO", GO),
    ("DK", DOCKER),
    ("K8", K8S),
    ("SH", SHELL),
]


def main() -> None:
    rows = []
    counts = {}
    i = 0
    for prefix, entries in ALL:
        counts[prefix] = len(entries)
        for e in entries:
            i += 1
            lang, framework, family, text, source, epc, action = e
            rows.append(
                {
                    "id": f"e{i:04d}",
                    "language": lang,
                    "framework": framework,
                    "family": family,
                    "text": text,
                    "source": source,
                    "expected_problem_class": epc,
                    "expected_action": action,
                }
            )

    OUT.write_text(
        "\n".join(json.dumps(r, ensure_ascii=False) for r in rows) + "\n",
        encoding="utf-8",
    )
    total = len(rows)
    print(f"wrote {total} rows to {OUT}")
    print("per-section counts:")
    for k, v in counts.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
